version: '3.8'

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "3128:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    command:
      - start-dev
      - --http-host=0.0.0.0
      - --http-port=8080
    networks:
      - keycloak-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - keycloak-net
    restart: unless-stopped

networks:
  keycloak-net:
    driver: bridge

volumes:
  ollama-data:
